name: Main-workflow
on: 
  workflow_dispatch:

jobs:
    some-other-step:
        runs-on: ubuntu-latest
        steps:
            - name: Setup PostgreSQL
              id: setuppostges1
              continue-on-error: true
              uses: tj-actions/install-postgresql@v3
              with:
                postgresql-version: 14
                
            - name: Setup PostgreSQL
              id: setuppostges2
              continue-on-error: true
              uses: tj-actions/install-postgresql@v3
              with:
                postgresql-version: 14

            - name: something
              run: exit 1 
                
    retry-on-failure:
        if: failure() && fromJSON(github.run_attempt) < 3
        needs: [some-other-step]
        runs-on: ubuntu-latest
        steps:
            - env:
                  GH_REPO: ${{ github.repository }}
                  GH_TOKEN: ${{ github.token }}
              run: gh workflow run retry_workfow.yml -F run_id=${{ github.run_id }}
