name: Input Files Build Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: environment
        required: true
        type: environment
      region:
        type: choice
        description: Select Region
        options:
          - "East US"
          - "West US"
        
env:
  PORT: 22

jobs:
  check:
    environment: ${{ github.event.inputs.environment }}
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: install expect
        run: |
           sudo apt install expect

