name: Main-workflow
on: 
  workflow_dispatch:

jobs:
    some-other-step:
        environment: dev
        runs-on: ubuntu-latest
        outputs:
            retry_limit: ${{ steps.redandsetenv.outputs.RETRY_ATTEMPT_LIMIT }}
            
        steps:
          - name: Something2
            run: | 
              echo ${{ vars.RETRY_ATTEMPT_LIMIT }} 
              echo ${{ fromJSON(github.run_attempt) }}
              
              if [[ ${{ fromJSON(github.run_attempt) }} != ${{ vars.RETRY_ATTEMPT_LIMIT }}  ]]; then
                echo "here not equal"
              fi;
              
              if [[ ${{ fromJSON(github.run_attempt) }} < ${{ vars.RETRY_ATTEMPT_LIMIT }}  ]]; then
                  echo "here less than"
              fi;
          
              if [[ ${{ fromJSON(github.run_attempt) }} == ${{ vars.RETRY_ATTEMPT_LIMIT }}  ]]; then
                echo "here equal"
              fi;


          - name: redandsetenv
            id: redandsetenv
            run: |
                RETRY_ATTEMPT_LIMIT=${{ vars.RETRY_ATTEMPT_LIMIT }}
                echo "RETRY_ATTEMPT_LIMIT=$RETRY_ATTEMPT_LIMIT" >> $GITHUB_OUTPUT

          - name: print
            id: print
            run: |
                echo ${{ steps.redandsetenv.outputs.RETRY_ATTEMPT_LIMIT }}
          
          - name: Something
            if : ${{ fromJSON(github.run_attempt) }} != ${{ vars.RETRY_ATTEMPT_LIMIT }} 
            run: exit 1

                
    retry-on-failure:
        environment: dev
        if: failure() &&  ( fromJSON(github.run_attempt) < needs.some-other-step.outputs.retry_limit )
        needs: [some-other-step]
        runs-on: ubuntu-latest
        steps:
            - env:
                  GH_REPO: ${{ github.repository }}
                  GH_TOKEN: ${{ github.token }}
              run: gh workflow run retry_workfow.yml -F run_id=${{ github.run_id }}

    retry-on-failure2:
        environment: dev
        if: failure()
        needs: [some-other-step]
        runs-on: ubuntu-latest
        steps:
            - name: print
              run: |
                echo ${{ needs.some-other-step.outputs.retry_limit }}
            
