name: Main-workflow
on: 
  workflow_dispatch:

jobs:
    some-other-step:
        environment: dev
        runs-on: ubuntu-latest
        steps:
          - name: Something2
            run: | 
              echo ${{ vars.RETRY_ATTEMPT_LIMIT }} 
              echo github.run_attempt
              echo ${{ fromJSON(github.run_attempt) }}
              
              if [[ ${{ fromJSON(github.run_attempt) }} != ${{ vars.RETRY_ATTEMPT_LIMIT }}  ]]; then
                echo "here not equal"
              fi;
              
              if [[ ${{ fromJSON(github.run_attempt) }} < ${{ vars.RETRY_ATTEMPT_LIMIT }}  ]]; then
                  echo "here less than"
              fi;
          
              if [[ ${{ fromJSON(github.run_attempt) }} == ${{ vars.RETRY_ATTEMPT_LIMIT }}  ]]; then
                echo "here equal"
              fi;
          
          - name: Something
            if : ${{ fromJSON(github.run_attempt) }} != ${{ vars.RETRY_ATTEMPT_LIMIT }} 
            run: exit 1
                
    retry-on-failure:
        if: failure() && (${{ fromJSON(github.run_attempt) }} < ${{ vars.RETRY_ATTEMPT_LIMIT }}) 
        needs: [some-other-step]
        runs-on: ubuntu-latest
        steps:
            - env:
                  GH_REPO: ${{ github.repository }}
                  GH_TOKEN: ${{ github.token }}
              run: gh workflow run retry_workfow.yml -F run_id=${{ github.run_id }}
