name: Input Files Build Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: environment
        required: true
        type: environment
      region:
        type: choice
        description: Select Region
        options:
          - "East US"
          - "West US"
        
env:
  PORT: 22

jobs:
  check:
    environment: ${{ github.event.inputs.environment }}
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 2.5.2
      - run: |
          cd /
          ls -l
          echo "root"
          cd /home
          ls -l
          echo "home"
          cd /home/runner/
          ls -l
          echo "runner"
          cd /home/runner/.m2/
          ls -l
          echo "m2"
          cat settings-security.xml

