name: Input Files Build Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: environment
        required: true
        type: environment
        
env:
  PORT: 22

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: print environment
        run: |
            echo ${{ github.event.inputs.environment }}
      - name: "create file"
        run: |
          touch text.txt
          echo "name">> text.txt
          sed 's/name/${{ secrets.name }}/' text.txt
      - name: "tar"
        run: tar -cvf file.tar text.txt 
      - name: "upload"
        uses: actions/upload-artifact@v2
        with:
          name: startup-scripts
          path: "file.tar"
      - name: Download Startup Scripts Artifact
        uses: actions/download-artifact@v2
        with:
          name: startup-scripts
